//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace SPE.Api.Proxys {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarCIPMod1OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarSolicitudPagov2OperationCompleted;
        
        /// <remarks/>
        public Service() {
            this.Url = System.Configuration.ConfigurationManager.AppSettings["PE_SERVER"] + System.Configuration.ConfigurationManager.AppSettings["PE_WSGENCIP"];
            //this.Url = "https://pre.pagoefectivo.pe/PagoEfectivoWSGeneralv2/service.asmx";
        }
        
        /// <remarks/>
        public event ConsultarCIPMod1CompletedEventHandler ConsultarCIPMod1Completed;
        
        /// <remarks/>
        public event ActualizarCIPMod1CompletedEventHandler ActualizarCIPMod1Completed;
        
        /// <remarks/>
        public event EliminarCIPMod1CompletedEventHandler EliminarCIPMod1Completed;
        
        /// <remarks/>
        public event GenerarCIPMod1CompletedEventHandler GenerarCIPMod1Completed;
        
        /// <remarks/>
        public event ConsultarSolicitudPagov2CompletedEventHandler ConsultarSolicitudPagov2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSConsultarCIPResponseMod1 ConsultarCIPMod1(BEWSConsultarCIPRequestMod1 request) {
            object[] results = this.Invoke("ConsultarCIPMod1", new object[] {
                        request});
            return ((BEWSConsultarCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsultarCIPMod1(BEWSConsultarCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsultarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSConsultarCIPResponseMod1 EndConsultarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSConsultarCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCIPMod1Async(BEWSConsultarCIPRequestMod1 request) {
            this.ConsultarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void ConsultarCIPMod1Async(BEWSConsultarCIPRequestMod1 request, object userState) {
            if ((this.ConsultarCIPMod1OperationCompleted == null)) {
                this.ConsultarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("ConsultarCIPMod1", new object[] {
                        request}, this.ConsultarCIPMod1OperationCompleted, userState);
        }
        
        private void OnConsultarCIPMod1OperationCompleted(object arg) {
            if ((this.ConsultarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCIPMod1Completed(this, new ConsultarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSActualizaCIPResponseMod1 ActualizarCIPMod1(BEWSActualizaCIPRequestMod1 request) {
            object[] results = this.Invoke("ActualizarCIPMod1", new object[] {
                        request});
            return ((BEWSActualizaCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginActualizarCIPMod1(BEWSActualizaCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ActualizarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSActualizaCIPResponseMod1 EndActualizarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSActualizaCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarCIPMod1Async(BEWSActualizaCIPRequestMod1 request) {
            this.ActualizarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void ActualizarCIPMod1Async(BEWSActualizaCIPRequestMod1 request, object userState) {
            if ((this.ActualizarCIPMod1OperationCompleted == null)) {
                this.ActualizarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("ActualizarCIPMod1", new object[] {
                        request}, this.ActualizarCIPMod1OperationCompleted, userState);
        }
        
        private void OnActualizarCIPMod1OperationCompleted(object arg) {
            if ((this.ActualizarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCIPMod1Completed(this, new ActualizarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSElimCIPResponseMod1 EliminarCIPMod1(BEWSElimCIPRequestMod1 request) {
            object[] results = this.Invoke("EliminarCIPMod1", new object[] {
                        request});
            return ((BEWSElimCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEliminarCIPMod1(BEWSElimCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EliminarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSElimCIPResponseMod1 EndEliminarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSElimCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarCIPMod1Async(BEWSElimCIPRequestMod1 request) {
            this.EliminarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void EliminarCIPMod1Async(BEWSElimCIPRequestMod1 request, object userState) {
            if ((this.EliminarCIPMod1OperationCompleted == null)) {
                this.EliminarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("EliminarCIPMod1", new object[] {
                        request}, this.EliminarCIPMod1OperationCompleted, userState);
        }
        
        private void OnEliminarCIPMod1OperationCompleted(object arg) {
            if ((this.EliminarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCIPMod1Completed(this, new EliminarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarCIPMod1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSGenCIPResponseMod1 GenerarCIPMod1(BEWSGenCIPRequestMod1 request) {
            object[] results = this.Invoke("GenerarCIPMod1", new object[] {
                        request});
            return ((BEWSGenCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerarCIPMod1(BEWSGenCIPRequestMod1 request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerarCIPMod1", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSGenCIPResponseMod1 EndGenerarCIPMod1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSGenCIPResponseMod1)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarCIPMod1Async(BEWSGenCIPRequestMod1 request) {
            this.GenerarCIPMod1Async(request, null);
        }
        
        /// <remarks/>
        public void GenerarCIPMod1Async(BEWSGenCIPRequestMod1 request, object userState) {
            if ((this.GenerarCIPMod1OperationCompleted == null)) {
                this.GenerarCIPMod1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarCIPMod1OperationCompleted);
            }
            this.InvokeAsync("GenerarCIPMod1", new object[] {
                        request}, this.GenerarCIPMod1OperationCompleted, userState);
        }
        
        private void OnGenerarCIPMod1OperationCompleted(object arg) {
            if ((this.GenerarCIPMod1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarCIPMod1Completed(this, new GenerarCIPMod1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarSolicitudPagov2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BEWSConsultarSolicitudResponse ConsultarSolicitudPagov2(BEWSConsultarSolicitudRequest request) {
            object[] results = this.Invoke("ConsultarSolicitudPagov2", new object[] {
                        request});
            return ((BEWSConsultarSolicitudResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginConsultarSolicitudPagov2(BEWSConsultarSolicitudRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ConsultarSolicitudPagov2", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public BEWSConsultarSolicitudResponse EndConsultarSolicitudPagov2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BEWSConsultarSolicitudResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarSolicitudPagov2Async(BEWSConsultarSolicitudRequest request) {
            this.ConsultarSolicitudPagov2Async(request, null);
        }
        
        /// <remarks/>
        public void ConsultarSolicitudPagov2Async(BEWSConsultarSolicitudRequest request, object userState) {
            if ((this.ConsultarSolicitudPagov2OperationCompleted == null)) {
                this.ConsultarSolicitudPagov2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarSolicitudPagov2OperationCompleted);
            }
            this.InvokeAsync("ConsultarSolicitudPagov2", new object[] {
                        request}, this.ConsultarSolicitudPagov2OperationCompleted, userState);
        }
        
        private void OnConsultarSolicitudPagov2OperationCompleted(object arg) {
            if ((this.ConsultarSolicitudPagov2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarSolicitudPagov2Completed(this, new ConsultarSolicitudPagov2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPSField;
        
        private string infoRequestField;
        
        /// <comentarios/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <comentarios/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <comentarios/>
        public string CIPS {
            get {
                return this.cIPSField;
            }
            set {
                this.cIPSField = value;
            }
        }
        
        /// <comentarios/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarSolicitudResponse {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string xmlField;
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarSolicitudRequest {
        
        private string cServField;
        
        private string cClaveField;
        
        private string xmlField;
        
        /// <comentarios/>
        public string cServ {
            get {
                return this.cServField;
            }
            set {
                this.cServField = value;
            }
        }
        
        /// <comentarios/>
        public string CClave {
            get {
                return this.cClaveField;
            }
            set {
                this.cClaveField = value;
            }
        }
        
        /// <comentarios/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSGenCIPResponseMod1 {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string xmlField;
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSGenCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string xmlField;
        
        /// <comentarios/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <comentarios/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <comentarios/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSElimCIPResponseMod1 {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string infoResponseField;
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSElimCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPField;
        
        private string infoRequestField;
        
        /// <comentarios/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <comentarios/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <comentarios/>
        public string CIP {
            get {
                return this.cIPField;
            }
            set {
                this.cIPField = value;
            }
        }
        
        /// <comentarios/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSActualizaCIPResponseMod1 {
        
        private string estadoField;
        
        private string mensajeField;
        
        private string infoResponseField;
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSActualizaCIPRequestMod1 {
        
        private string codServField;
        
        private string firmaField;
        
        private string cIPField;
        
        private System.DateTime fechaExpiraField;
        
        private string infoRequestField;
        
        /// <comentarios/>
        public string CodServ {
            get {
                return this.codServField;
            }
            set {
                this.codServField = value;
            }
        }
        
        /// <comentarios/>
        public string Firma {
            get {
                return this.firmaField;
            }
            set {
                this.firmaField = value;
            }
        }
        
        /// <comentarios/>
        public string CIP {
            get {
                return this.cIPField;
            }
            set {
                this.cIPField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaExpira {
            get {
                return this.fechaExpiraField;
            }
            set {
                this.fechaExpiraField = value;
            }
        }
        
        /// <comentarios/>
        public string InfoRequest {
            get {
                return this.infoRequestField;
            }
            set {
                this.infoRequestField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BEWSConsultarCIPResponseMod1 {
        
        private string xMLField;
        
        private string estadoField;
        
        private string mensajeField;
        
        private string infoResponseField;
        
        /// <comentarios/>
        public string XML {
            get {
                return this.xMLField;
            }
            set {
                this.xMLField = value;
            }
        }
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <comentarios/>
        public string InfoResponse {
            get {
                return this.infoResponseField;
            }
            set {
                this.infoResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ConsultarCIPMod1CompletedEventHandler(object sender, ConsultarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSConsultarCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSConsultarCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ActualizarCIPMod1CompletedEventHandler(object sender, ActualizarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSActualizaCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSActualizaCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void EliminarCIPMod1CompletedEventHandler(object sender, EliminarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSElimCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSElimCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GenerarCIPMod1CompletedEventHandler(object sender, GenerarCIPMod1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarCIPMod1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarCIPMod1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSGenCIPResponseMod1 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSGenCIPResponseMod1)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ConsultarSolicitudPagov2CompletedEventHandler(object sender, ConsultarSolicitudPagov2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarSolicitudPagov2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarSolicitudPagov2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BEWSConsultarSolicitudResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BEWSConsultarSolicitudResponse)(this.results[0]));
            }
        }
    }
}
